version: "3.3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25676:25676"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "test"